pipeline:
  dockerBuild:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: git.gomarcd.dev/gomarcd/supman
      tag: latest
      logins:
        - registry: docker.io
          username:
            from_secret: dockerhubuser
          password:
            from_secret: dockerhubpass