pipeline:
  build-and-push-image:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: gomarcd/supman
      tag: latest
      logins:
        - registry: quay.io
          username:
            from_secret: quayuser
          password:
            from_secret: quaypass
        - registry: docker.io
          username:
            from_secret: dockeruser
          password:
            from_secret: dockerpass

    # settings:
    #   repo: quay.io/gomarcd/supman
    #   registry: quay.io
    #   tag: latest
    #   username:
    #     from_secret: quayuser
    #   password:
    #     from_secret: quaypass