pipeline:
  dockerBuild:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: git.gomarcd.dev/gomarcd/supman
      tag: latest
      logins:
        - registry: https://index.docker.io/v1/
          username:
            from_secret: DockerHubUser
          password:
            from_secret: DockerHubPass