pipeline:
  build-and-push-image:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: quay.io/gomarcd/supman,gomarcd/supman
      tag: latest
      logins:
        - registry: quay.io
          username:
            from_secret: quayuser
          password:
            from_secret: quaypass
        - registry: docker.io
          username:
            from_secret: dockeruser
          password:
            from_secret: dockerpass
  deploy:
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_username
      key:
        from_secret: ssh_key
      script:
        - cd /home/md/docker/supman && docker compose pull && docker compose up -d --force-recreate --remove-orphans