pipeline:
  build-Dockerfile:
    image: plugins/docker
    commands:
      - docker build --no-cache -t gomarcd/supman .
  push-DockerHub:
    image: plugins/docker
    settings:
      repo: gomarcd/supman
      username:
        from_secret: ${DockerHubUser}
      password:
        from_secret: ${DockerHubPass}
      tags: latest