pipeline:
  dockerBuild:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: git.gomarcd.dev/gomarcd/supman
      registry: quay.io
      tag: latest
      username:
        from_secret: quayuser
      password:
        from_secret: quaypass