pipeline:
  build-and-push-image:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: quay.io/gomarcd/supman,docker.io/gomarcd/supman
      tag: latest
      logins:
        - registry: quay.io
          username:
            from_secret: quayuser
          password:
            from_secret: quaypass
        - registry: https://index.docker.io/v1/
          username:
            from_secret: dockerhubuser
          password:
            from_secret: dockerhubpass

    # settings:
    #   repo: quay.io/gomarcd/supman
    #   registry: quay.io
    #   tag: latest
    #   username:
    #     from_secret: quayuser
    #   password:
    #     from_secret: quaypass