pipeline:
  build-Dockerfile:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: git.gomarcd.dev/gomarcd/supman
      tag: latest
      logins:
        - registry: docker.io
          username:
            from_secret: DockerHubUser
          password:
            from_secret: DockerHubPass
        - registry: quay.io
          username:
            from_secret: QuayUser
          password:
            from_secret: QuayPass
 #   commands:
 #     - docker build -t gomarcd/supman .
 # push-DockerHub:
 #   image: woodpeckerci/plugin-docker-buildx
 #   settings:
 #     repo: gomarcd/supman
     # username:
     #   from_secret: ${DockerHubUser}
     # password:
     #   from_secret: ${DockerHubPass}
 #     tags: latest