pipeline:
  build-and-push-image:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: quay.io/gomarcd/supman
      registry: quay.io
      tag: latest
      username:
        from_secret: quayuser
      password:
        from_secret: quaypass