pipeline:
  dockerBuild:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: git.gomarcd.dev/gomarcd/supman
      registry: docker.io
      tag: latest
      username:
        from_secret: dockerhubuser
      password:
        from_secret: dockerhubpass