pipeline:
  dockerBuild:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: quay.io/gomarcd/supman
      tag: latest
      username:
        from_secret: quayuser
      password:
        from_secret: quaypass