version: "3"
services:
  nginx:
    image: nginx:alpine
    container_name: supman-www
    working_dir: /var/www
    restart: always
    ports:
      - "8282:80"
    depends_on:
      - app
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./public:/var/www/public
      - ./nginx/logs:/var/log/nginx/
    networks:
      - supman

  app:
    build:
     context: .
     dockerfile: Dockerfile
    container_name: supman-php
    working_dir: /var/www
    restart: always
    user: 1000:1000
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www
    networks:
      - supman

  redis:
    image: redis:latest
    container_name: supman-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    networks:
      - supman

networks:
  supman:
    driver: bridge
