version: "3"
services:
  supman-docker:
    build:
      context: .
      dockerfile: Dockerfile
    image: gomarcd/supman
    container_name: supman
    working_dir: /var/www
    restart: always
    volumes:
      - "./src/cron.log:/var/log/cron.log"
      - "./src/.env:/var/www/.env"
      - "./src/supervisord.log:/var/log/supervisor/supervisord.log"
    ports:
      - "8282:80"
    networks:
      - supman
networks:
  supman:
    driver: bridge
