version: "3"
services:
  supman-docker:
    build:
      context: .
      dockerfile: Dockerfile
    image: supman-docker
    container_name: supman
    working_dir: /var/www
    restart: always
    ports:
      - "8282:80"
    networks:
      - supman

  # redis:
  #   image: redis:latest
  #   container_name: supman-redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./redis-data:/data
  #   networks:
  #     - supman

networks:
  supman:
    driver: bridge