version: "3"
services:
  supman:
    build:
      context: .
      dockerfile: Dockerfile
    image: gomarcd/supman
    container_name: supman
    restart: always
    volumes:
      - "./.env:/var/www/.env"
    ports:
      - "8080:80"